# Generated by Django 5.2.1 on 2025-05-09 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scale", models.CharField(max_length=100)),
                ("hit_range", models.CharField(max_length=100)),
                ("electricity", models.CharField(max_length=100)),
                ("humid", models.CharField(max_length=100)),
                ("functions", models.JSONField(default=list)),
                ("setting_file", models.JSONField(default=dict)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("download_count", models.IntegerField(default=0)),
                ("stars", models.FloatField(default=0.0)),
            ],
        ),
    ]
