# Generated by Django 5.2.1 on 2025-05-09 14:16

import container.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="functions",
            field=models.JSONField(
                default=container.models.Container.default_functions
            ),
        ),
    ]
