# Generated by Django 5.2.1 on 2025-05-09 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0002_alter_container_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
