# Generated by Django 5.2.1 on 2025-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0003_alter_container_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="creater",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="container",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
