# Generated by Django 5.2.1 on 2025-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0004_container_creater_container_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="notes",
            field=models.CharField(default="", max_length=1600),
        ),
    ]
