# Generated by Django 5.2.1 on 2025-05-09 18:00

import container.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0005_container_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="added_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="creater",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="download_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="electricity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="functions",
            field=models.JSONField(
                blank=True,
                default=container.models.Container.default_functions,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="hit_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="humid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="scale",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="setting_file",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="stars",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
