# Generated by Django 5.2.1 on 2025-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('기본형', '기본형'), ('표준형', '표준형'), ('고급형', '고급형')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('시작', '시작'), ('중지됨', '중지됨')], max_length=10)),
                ('base_config', models.FileField(blank=True, null=True, upload_to='base_configs/')),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
