# Generated by Django 5.2.1 on 2025-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("시작", "시작"), ("중지됨", "중지됨")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("기본형", "기본형"),
                    ("표준형", "표준형"),
                    ("고급형", "고급형"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
